version: '3.9'

services:
  emobiletest:
    build: ./

    command: ./wait-for-postgres.sh db ./emobiletest 
    
    ports: 
      - 8080:8080
    container_name: emobiletest
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db

  db:

    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
     

      
    ports:
      - "5432:5432"
    volumes: 
      - ./.dbdata/postgres/data:/var/lib/postgresql/data